data_dir: /home/xuanming/kaggle/Detect Sleep States/child-mind-institute-detect-sleep-states
processed_dir: /home/xuanming/kaggle/Detect Sleep States/child-mind-institute-detect-sleep-states/processed_data
output_dir: /home/xuanming/kaggle/Detect Sleep States/output
model_dir: /home/xuanming/kaggle/Detect Sleep States/output/train
sub_dir: ./