data_dir: /root/autodl-tmp/kaggle-detect-sleep/data/child-mind-institute-detect-sleep-states
processed_dir: /root/autodl-tmp/kaggle-detect-sleep/data/processed_data
output_dir: /root/autodl-tmp/kaggle-detect-sleep/output
model_dir: /root/autodl-tmp/kaggle-detect-sleep/output/train
sub_dir: ./