data_dir: /home/xuanming/kaggle/Detect Sleep States/kaggle-detect-sleep/data/
processed_dir: /home/xuanming/kaggle/Detect Sleep States/kaggle-detect-sleep/data/processed_data
output_dir: /home/xuanming/kaggle/Detect Sleep States/kaggle-detect-sleep/output/
model_dir: /home/xuanming/kaggle/Detect Sleep States/kaggle-detect-sleep/output/train
sub_dir: ./
