# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: inference
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - model: Spec2DCNN
  - feature_extractor: CNNSpectrogram
  - decoder: UNet1DDecoder
  - encoder: UNet++

exp_name: dummy
phase: test
weight:
  exp_name: ${exp_name}
  run_name: single

seed: 42
duration: 11520 # durationは32の倍数
downsample_rate: 2 # durationをdownsample_rateで割った値がnum_framesになる
upsample_rate: 1
batch_size: 16
num_workers: 2
use_amp: true
overlap_interval: 768
weight_dir: ./
config_dir: ./
suffix: 0

# augmentation
augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4

# post_process
post_process:
  score_th: 0.02
  distance: 10
  gap: 180
  quantile: 0.9
  version: v2
  
# label
labels:
  - "awake"
  - "event_onset"
  - "event_wakeup"

# feature
features:
  - "anglez"
  - "enmo"
  # - "step"
  # - "month_sin"
  # - "month_cos"
  - "hour_sin"
  - "hour_cos"
  # - "minute_sin"
  # - "minute_cos"
  # - "anglez_sin"
  # - "anglez_cos"

# criterion
loss:
  name: "bce"
  alpha: 1.0
  gamma: 2.0
  weight: 0