# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - model: Combined
  - feature_extractor: PrecFeatureExtractor
  - decoder: cnn_transformer
  - encoder: Residual_lstm
  - split: fold_1

seed: 42
exp_name: dummy
duration: 5760 # duration * 5 = 秒数
downsample_rate: 1
upsample_rate: 1
overlap_interval: 720

#For model
#sequence_length : duration + 2 * overlap_interval
# 需要满足： (duration + 2 * overlap_interval) / chunks 是偶数
sequence_length: 0
chunks: 480
num_classes: 3

# training
epoch: 150
batch_size: 16
num_workers: 16
accelerator: auto
use_amp: true
debug: false
gradient_clip_val: 1.0
accumulate_grad_batches: 1
monitor: val_score2
monitor_mode: max
check_val_every_n_epoch: 1

# Dataset
offset: 30
sigma: 20
bg_sampling_rate: 0.5

# augmentation
augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4
  
# post_process
post_process:
  score_th: 0.02
  distance: 10
  gap: 120
  quantile: 0.7

# label
labels:
  - "awake"
  - "event_onset"
  - "event_wakeup"

# feature
features:
  - "anglez"
  - "enmo"
  # - "step"
  # - "month_sin"
  # - "month_cos"
  - "hour_sin"
  - "hour_cos"
  #- "minute_sin"
  #- "minute_cos"
  #- "anglez_sin"
  #- "anglez_cos"

# optimizer
optimizer:
  lr: 5e-4

# scheduler
scheduler:
  num_warmup_steps: 0.2
  
# criterion
loss:
  name: "bce"
  alpha: 1.0
  gamma: 2.0
  weight: 1
