# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - model: Spec2DCNN
  - feature_extractor: CNNSpectrogram
  - decoder: UNet1DDecoder
  - encoder: UNet
  - split: fold_0

seed: 42
exp_name: dummy
duration: 5760 # duration * 5 = 秒数
downsample_rate: 2
upsample_rate: 1

# training
epoch: 50
batch_size: 16
num_workers: 4
accelerator: auto
use_amp: true
debug: false
gradient_clip_val: 1.0
accumulate_grad_batches: 1
monitor: val_score2
monitor_mode: max
check_val_every_n_epoch: 1

# Dataset
offset: 10
sigma: 10
bg_sampling_rate: 0.5

# augmentation
augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4
  
# post_process
post_process:
  score_th: 0.02
  distance: 10
  gap: 180
  quantile: 0.9

# label
labels:
  - "awake"
  - "event_onset"
  - "event_wakeup"

# feature
features:
  - "anglez"
  - "enmo"
  # - "month_sin"
  # - "month_cos"
  - "hour_sin"
  - "hour_cos"
  # - "minute_sin"
  # - "minute_cos"

# optimizer
optimizer:
  lr: 0.0005

# scheduler
scheduler:
  num_warmup_steps: 0
  
# criterion
loss:
  name: "bce"
  alpha: 1.0
  gamma: 2.0
  weight: 0
